{{- range .Values.teams }}
{{- $serviceAccountRef := .serviceAccountRef -}}
{{- $seedNamespace := .seedNamespace -}}
{{- range .namespaces }}
apiVersion: v1
kind: Namespace
metadata:
  name: "{{ .namespace }}"
spec:
  finalizers:
  - kubernetes
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ .namespace }}"
subjects: 
- kind: ServiceAccount
  name: "{{ $serviceAccountRef }}"
  namespace: "{{ $seedNamespace }}"
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io  
---
{{- end }}
{{- end }}
